# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets # noqa


class Ui_InfoPage(object):
    def setupUi(self, background):
        background.setObjectName("background")
        background.resize(1440, 900)
        background.setStyleSheet("background-color: #f1dff2;\n" "")
        self.menu_button = QtWidgets.QPushButton(background)
        self.menu_button.setGeometry(QtCore.QRect(40, 40, 151, 41))
        self.menu_button.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #eec7f0;\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #ce99d1;\n"
            "}\n"
            ""
        )
        self.menu_button.setObjectName("menu_button")
        self.info_page_label = QtWidgets.QLabel(background)
        self.info_page_label.setGeometry(QtCore.QRect(440, 80, 551, 81))
        self.info_page_label.setStyleSheet(
            "QLabel {\n"
            "    background-color: #eec7f0;\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "    padding: 10px;\n"
            "}\n"
            ""
        )
        self.info_page_label.setObjectName("info_page_label")
        self.textEdit = QtWidgets.QTextEdit(background)
        self.textEdit.setGeometry(QtCore.QRect(130, 238, 1181, 511))
        self.textEdit.setStyleSheet(
            "QTextEdit {\n"
            "    background-color: #eec7f0;\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "    padding: 10px;\n"
            "}\n"
            ""
        )
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(background)
        QtCore.QMetaObject.connectSlotsByName(background)

    def retranslateUi(self, background):
        _translate = QtCore.QCoreApplication.translate
        background.setWindowTitle(_translate("background", "Form"))
        self.menu_button.setText(_translate("background", "Back to menu"))
        self.info_page_label.setText(
            _translate(
                "background",
                '<html><head/><body><p align="center"><span style=" font-size:48pt; font-weight:600; font-style:italic;">Info page</span></p></body></html>', # noqa
            )
        )
        self.textEdit.setHtml(
            _translate(
                "background",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n' # noqa
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n' # noqa
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n" # noqa
                '<p align="center" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Load up on guns, bring your friends<br />It\'s fun to lose and to pretend<br />She\'s over-bored and self assured<br />Oh no, I know a dirty word<br />Hello, hello, hello, how low<br />Hello, hello, hello, how low<br />Hello, hello, hello, how low<br />Hello, hello, hello</p>\n' # noqa
                '<p align="center" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">With the lights out, it\'s less dangerous<br />Here we are now, entertain us<br />I feel stupid and contagious<br />Here we are now, entertain us<br />A mulatto, an albino, a mosquito, my libido<br />Yeah, hey, yay</p>\n' # noqa
                '<p align="center" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">I\'m worse at what I do best<br />And for this gift I feel blessed<br />Our little group has always been<br />And always will until the end<br />Hello, hello, hello, how low<br />Hello, hello, hello, how low<br />Hello, hello, hello, how low<br />Hello, hello, hello</p>\n' # noqa
                '<p align="center" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">With the lights out, it\'s less dangerous<br />Here we are now, entertain us<br />I feel stupid and contagious<br />Here we are now, entertain us<br />A mulatto, an albino, a mosquito, my libido<br />Yeah, hey, yay</p>\n' # noqa
                '<p align="center" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">And I forget just why I taste<br />Oh yeah, I guess it makes me smile<br />I found it hard, it\'s hard to find<br />Oh well, whatever, never mind<br />Hello, hello, hello, how low<br />Hello, hello, hello, how low<br />Hello, hello, hello, how low<br />Hello, hello, hello</p>\n' # noqa
                '<p align="center" style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">With the lights out, it\'s less dangerous<br />Here we are now, entertain us<br />I feel stupid and contagious<br />Here we are now, entertain us<br />A mulatto, an albino, a mosquito, my libido<br />A denial, a denial, a denial, a denial, a denial<br />A denial, a denial, a denial, a denial</p></body></html>', # noqa
            )
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    background = QtWidgets.QWidget()
    ui = Ui_InfoPage()
    ui.setupUi(background)
    background.show()
    sys.exit(app.exec_())
