# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'self_care_tips.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets # noqa


class Ui_background(object):
    def setupUi(self, background):
        background.setObjectName("background")
        background.resize(690, 653)
        background.setStyleSheet(
            "background-color: #f1dff2;\n" "border: #141414;\n" "border-radius: 10px;" # noqa
        )
        self.self_care_tips_label = QtWidgets.QLabel(background)
        self.self_care_tips_label.setGeometry(QtCore.QRect(470, 100, 491, 91))
        self.self_care_tips_label.setStyleSheet(
            "QLabel {\n"
            "    background-color: #eec7f0; \n"
            "    color: black;\n"
            "    font-size: 16px;\n"
            "    padding: 10px;\n"
            "    border-radius: 5px;\n"
            "    border: 2px solid black;\n"
            "}\n"
            ""
        )
        self.self_care_tips_label.setObjectName("self_care_tips_label")
        self.menuButton = QtWidgets.QPushButton(background)
        self.menuButton.setGeometry(QtCore.QRect(60, 50, 141, 41))
        self.menuButton.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #eec7f0;\n"
            "    color: black;\n"
            "    padding: 10px;\n"
            "    border-radius: 5px;\n"
            "    border: 2px solid black;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #ce99d1;\n"
            "}\n"
            ""
        )
        self.menuButton.setObjectName("menuButton")
        self.stackedWidget = QtWidgets.QStackedWidget(background)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 250, 1121, 481))
        self.stackedWidget.setStyleSheet(
            "QStackedWidget {\n"
            "    background-color: #eec7f0;\n"
            "}\n"
            "\n"
            "QLabel {\n"
            "    color: black;\n"
            "    background-color: #eec7f0;\n"
            "    font-size: 25px;\n"
            "    font-weight: bold;\n"
            "    padding: 10px;\n"
            "    border: 3px solid black;\n"
            "    border-radius: 10px;\n"
            "}\n"
            ""
        )
        self.stackedWidget.setObjectName("stackedWidget")

        self.createPages() # c

        self.pushButton = QtWidgets.QPushButton(background)
        self.pushButton.setGeometry(QtCore.QRect(1160, 720, 113, 41))
        self.pushButton.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #eec7f0;\n"
            "    color: black;\n"
            "    padding: 10px;\n"
            "    border-radius: 5px;\n"
            "    border: 2px solid black;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #ce99d1;\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        
        # Previous Button
        self.pushButton_2 = QtWidgets.QPushButton(background)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 720, 113, 41))
        self.pushButton_2.setStyleSheet(
            "QPushButton {\n"
            "    background-color: #eec7f0;\n"
            "    color: black;\n"
            "    padding: 10px;\n"
            "    border-radius: 5px;\n"
            "    border: 2px solid black;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #ce99d1;\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")

        # Connect buttons to methods
        self.pushButton.clicked.connect(self.goNext)
        self.pushButton_2.clicked.connect(self.goPrevious)

        self.retranslateUi(background)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(background)

    def createPages(self):
        """Create and add pages to the stacked widget."""
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 25, 1061, 431))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 1061, 421))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)

        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setGeometry(QtCore.QRect(29, 29, 1061, 421))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_4)

        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(29, 29, 1061, 421))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_3)

    def goNext(self):
        """Move to next page"""
        current_index = self.stackedWidget.currentIndex()
        if current_index < self.stackedWidget.count() - 1:
            self.stackedWidget.setCurrentIndex(current_index + 1)

    def goPrevious(self):
        """Move to previous page"""
        current_index = self.stackedWidget.currentIndex()
        if current_index > 0:
            self.stackedWidget.setCurrentIndex(current_index - 1)

    def retranslateUi(self, background):
        _translate = QtCore.QCoreApplication.translate
        background.setWindowTitle(_translate("background", "Form"))
        self.self_care_tips_label.setText(
            _translate(
                "background",
                '<html><head/><body><p align="center"><span style=" font-size:36pt; font-weight:600; font-style:italic;">Self care tips</span></p></body></html>',  # noqa
            )
        )
        self.menuButton.setText(_translate("background", "Back to menu"))
        self.label.setText(
            _translate(
                "background",
                '<html><head/><body><p align="center"><span style=" font-size:25pt;">page 1</span></p></body></html>',  # noqa
            )
        )
        self.label_2.setText(
            _translate(
                "background",
                '<html><head/><body><p align="center"><span style=" font-size:25pt;">page 2</span></p></body></html>',  # noqa
            )
        )
        self.label_3.setText(
            _translate(
                "background",
                '<html><head/><body><p align="center"><span style=" font-size:25pt;">page 3</span></p></body></html>',  # noqa
            )
        )
        self.label_4.setText(
            _translate(
                "background",
                '<html><head/><body><p align="center"><span style=" font-size:25pt;">page 4</span></p></body></html>',  # noqa
            )
        )
        self.pushButton.setText(_translate("background", "Next"))
        self.pushButton_2.setText(_translate("background", "Previous"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    background = QtWidgets.QWidget()
    ui = Ui_background()
    ui.setupUi(background)
    background.show()
    sys.exit(app.exec_())