# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'self_care_tips.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelfCarePage(object):
    def setupUi(self, background):
        # setting the background
        background.setObjectName("background")
        background.resize(1440, 900)

        # setting the main label of the page
        self.self_care_tips_label = QtWidgets.QLabel(background)
        self.self_care_tips_label.setGeometry(QtCore.QRect(440, 80, 551, 81))
        self.self_care_tips_label.setText("Self Care Tips")
        self.self_care_tips_label.setAlignment(QtCore.Qt.AlignCenter)
        self.self_care_tips_label.setStyleSheet(
            "QLabel {\n"
            "    color: black;\n"
            "    font-size: 48px;\n"
            "    font-style: italic;"
            "    font-weight: bold;"
            "    padding: 10px;\n"
            "    border-radius: 5px;\n"
            "    border: 2px solid black;\n"
            "}\n"
            ""
        )
        self.self_care_tips_label.setObjectName("self_care_tips_label")

        # back to menu button
        self.btn_menu = QtWidgets.QPushButton(background)
        self.btn_menu.setGeometry(QtCore.QRect(40, 40, 151, 41))
        self.btn_menu.setObjectName("btn_menu")
        self.btn_menu.setText("Back to menu")
        self.btn_menu.setStyleSheet(
            "QPushButton {\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #d3d3d3;\n"
            "}\n"
            ""
        )
        self.btn_menu.clicked.connect(background.close)

        # the widget which holds all the pages(with self care tips on them)
        self.stackedWidget = QtWidgets.QStackedWidget(background)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 200, 1121, 481))
        self.stackedWidget.setStyleSheet(
            "QStackedWidget {\n"
            "    background-color: #ECECEC;\n"
            "}\n"
            "\n"
            "QLabel {\n"
            "    color: black;\n"
            "    font-size: 25px;\n"
            "    font-weight: bold;\n"
            "    padding: 10px;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 10px;\n"
            "}\n"
            ""
        )
        self.stackedWidget.setObjectName("stackedWidget")

        self.createPages()

        # Next button
        self.pushButton = QtWidgets.QPushButton(background)
        self.pushButton.setGeometry(QtCore.QRect(1160, 680, 113, 41))
        self.pushButton.setStyleSheet(
            "QPushButton {\n"
            "    color: black;\n"
            "    padding: 10px;\n"
            "    border-radius: 5px;\n"
            "    border: 2px solid black;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #d3d3d3;\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.goNext)
        self.pushButton.setText("Next")

        # Previous Button
        self.pushButton_2 = QtWidgets.QPushButton(background)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 680, 113, 41))
        self.pushButton_2.setStyleSheet(
            "QPushButton {\n"
            "    color: black;\n"
            "    padding: 10px;\n"
            "    border-radius: 5px;\n"
            "    border: 2px solid black;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #d3d3d3;\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.goPrevious)
        self.pushButton_2.setText("Previous")

        self.retranslateUi(background)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(background)

    def createPages(self):
        """Create and add pages to the stacked widget."""
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 30, 1061, 431))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page)
        self.label.setText("page uno")
        self.label.setAlignment(QtCore.Qt.AlignCenter)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 1061, 431))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.label_2.setText("page dos")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)

        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_4")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 1061, 431))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_3)
        self.label_3.setText("page tres")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)

        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 1061, 431))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_4)
        self.label_4.setText("page quatro")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)

    def goNext(self):
        """Move to next page"""
        current_index = self.stackedWidget.currentIndex()
        if current_index < self.stackedWidget.count() - 1:
            self.stackedWidget.setCurrentIndex(current_index + 1)

    def goPrevious(self):
        """Move to previous page"""
        current_index = self.stackedWidget.currentIndex()
        if current_index > 0:
            self.stackedWidget.setCurrentIndex(current_index - 1)

    def retranslateUi(self, background):
        _translate = QtCore.QCoreApplication.translate
        background.setWindowTitle(_translate("background", "Form"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    background = QtWidgets.QWidget()
    ui = Ui_SelfCarePage()
    ui.setupUi(background)
    background.show()
    sys.exit(app.exec_())
