# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)  # Set window size

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Table Widget for displaying task statistics
        self.tbl_stats = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_stats.setGeometry(QtCore.QRect(130, 240, 1200, 430))
        self.tbl_stats.setObjectName("tbl_stats")
        self.tbl_stats.setColumnCount(4)  # Define 4 columns
        self.tbl_stats.setRowCount(0)  # No rows initially
        self.tbl_stats.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem("Task Name"))
        self.tbl_stats.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem("Points"))
        self.tbl_stats.setHorizontalHeaderItem(2, QtWidgets.QTableWidgetItem("Date"))
        self.tbl_stats.setHorizontalHeaderItem(3, QtWidgets.QTableWidgetItem("Total points collected"))
        self.tbl_stats.setColumnWidth(0, 299)
        self.tbl_stats.setColumnWidth(1, 299)
        self.tbl_stats.setColumnWidth(2, 299)
        self.tbl_stats.setColumnWidth(3, 299)
        self.tbl_stats.setStyleSheet("""
            QTableWidget {
                border: 2px solid black;
                background-color: #ECECEC;
                border-radius: 5px;
            }
            
            QHeaderView::section {
                background-color: #d3d3d3;
                font-size: 14pt; 
                font-weight: bold;
                color: black;
                padding: 5px;
            }
        """)


        # Buttons for closing the page
        self.btn_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu.setGeometry(QtCore.QRect(40, 40, 151, 41))
        self.btn_menu.setObjectName("btn_menu")
        self.btn_menu.setText("Back to menu")
        self.btn_menu.setStyleSheet(
            "QPushButton {\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #d3d3d3;\n"
            "}\n"
            ""
        )
        self.btn_menu.clicked.connect(MainWindow.close)  # Close window on click

        # Main page label 
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setGeometry(QtCore.QRect(440, 80, 551, 81))
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_title.setText("Statistics")
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setStyleSheet(
            "QLabel {"
            "    font-size: 48pt;"
            "    font-style: italic;"
            "    font-weight: bold;"
            "    color: black;"
            "    border: 2px solid black;"
            "    border-radius: 5px;"
            "    padding: 10px;"
            "}"
        )

        # Set the main layout, menu bar, and status bar
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)  # Initialize the UI setup
    MainWindow.show()  # Display the window
    sys.exit(app.exec_())  # Execute the application
