# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pickle


class Ui_TaskPage(object):
    def setupUi(self, TaskPage):
        TaskPage.setObjectName("TaskPage")
        TaskPage.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(TaskPage)
        self.centralwidget.setObjectName("centralwidget")
        
        # Points label
        self.pointsLabel = QtWidgets.QLabel(self.centralwidget)
        self.pointsLabel.setGeometry(QtCore.QRect(920, 110, 60, 16))
        self.pointsLabel.setObjectName("pointsLabel")
        
        # "To-Do" Label
        self.toDoLabel = QtWidgets.QLabel(self.centralwidget)
        self.toDoLabel.setGeometry(QtCore.QRect(660, 90, 81, 31))
        self.toDoLabel.setObjectName("toDoLabel")
        
        # Reset Button
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(850, 620, 131, 31))
        self.resetButton.setObjectName("resetButton")
        
        # Save Button
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(850, 590, 131, 31))
        self.saveButton.setObjectName("saveButton")
        
        # Task list view
        self.taskList = QtWidgets.QListWidget(self.centralwidget)
        self.taskList.setGeometry(QtCore.QRect(440, 150, 551, 411))
        self.taskList.setObjectName("taskList")
        
        TaskPage.setCentralWidget(self.centralwidget)
        
        # Menu bar
        self.menubar = QtWidgets.QMenuBar(TaskPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        TaskPage.setMenuBar(self.menubar)
        
        # Status bar
        self.statusbar = QtWidgets.QStatusBar(TaskPage)
        self.statusbar.setObjectName("statusbar")
        TaskPage.setStatusBar(self.statusbar)

        self.retranslateUi(TaskPage)
        QtCore.QMetaObject.connectSlotsByName(TaskPage)

    def retranslateUi(self, TaskPage):
        _translate = QtCore.QCoreApplication.translate
        TaskPage.setWindowTitle(_translate("TaskPage", "Task Page"))
        self.pointsLabel.setText(_translate("TaskPage", "Points: 0"))
        self.toDoLabel.setText(_translate("TaskPage", "TO-DO LIST"))
        self.resetButton.setText(_translate("TaskPage", "Reset Everything"))
        self.saveButton.setText(_translate("TaskPage", "Save Progress"))

    def saveProgress(self):
        data = {
            'tasks': [self.taskList.item(i).text() for i in range(self.taskList.count())],
            'points': self.pointsLabel.text().split(': ')[1]
        }
        with open('task_progress.pkl', 'wb') as file:
            pickle.dump(data, file)

    def loadProgress(self):
        try:
            with open('task_progress.pkl', 'rb') as file:
                data = pickle.load(file)
                tasks = data.get('tasks', [])
                points = data.get('points', '0')
                
                for task in tasks:
                    self.taskList.addItem(task)
                    
                self.pointsLabel.setText(f"Points: {points}")
        except FileNotFoundError:
            pass  # Handle if no save file exists

    def resetEverything(self):
        self.taskList.clear()
        self.pointsLabel.setText("Points: 0")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TaskPage = QtWidgets.QMainWindow()
    ui = Ui_TaskPage()
    ui.setupUi(TaskPage)
    ui.loadProgress()  # Load progress at the start
    TaskPage.show()
    sys.exit(app.exec_())
