# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taskPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import pickle


class Ui_TaskPage(object):
    def setupUi(self, TaskPage):
        TaskPage.setObjectName("TaskPage")
        TaskPage.resize(1440, 900)

        # Create a central widget for the task page
        self.centralwidget = QtWidgets.QWidget(TaskPage)
        self.centralwidget.setObjectName("centralwidget")
        
        # Points label to display the user's score
        self.pointsLabel = QtWidgets.QLabel(self.centralwidget)
        self.pointsLabel.setGeometry(QtCore.QRect(1000, 280, 250, 100))
        self.pointsLabel.setObjectName("pointsLabel")
        self.pointsLabel.setText("Points: 0")
        self.pointsLabel.setStyleSheet(
            "QLabel {"
            "    font-size: 30pt;"
            "    color: black;"
            "    border: 2px solid black;"
            "    border-radius: 5px;"
            "    padding: 10px;"
            "}"
        )
        
        # Label for the "To-Do" list heading
        self.toDoLabel = QtWidgets.QLabel(self.centralwidget)
        self.toDoLabel.setGeometry(QtCore.QRect(440, 80, 551, 81))
        self.toDoLabel.setObjectName("toDoLabel")
        self.toDoLabel.setText("To-Do List")
        self.toDoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.toDoLabel.setStyleSheet(
            "QLabel {"
            "    font-size: 48pt;"
            "    font-style: italic;"
            "    font-weight: bold;"
            "    color: black;"
            "    border: 2px solid black;"
            "    border-radius: 5px;"
            "    padding: 10px;"
            "}"
        )
        
        # Reset button that clears tasks and resets points
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(1000, 500, 150, 50))
        self.resetButton.setObjectName("resetButton")
        self.resetButton.setText("Reset Everything")
        self.resetButton.setStyleSheet(
            "QPushButton {\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #d3d3d3;\n"
            "}\n"
            ""
        )
        
        # Save button that stores progress to a file
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(1000, 600, 150, 50))
        self.saveButton.setObjectName("saveButton")
        self.saveButton.setText("Save Progress")
        self.saveButton.setStyleSheet(
            "QPushButton {\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #d3d3d3;\n"
            "}\n"
            ""
        )
        
        # Task list view using QListWidget with checkboxes for each task
        self.taskList = QtWidgets.QListWidget(self.centralwidget)
        self.taskList.setGeometry(QtCore.QRect(200, 200, 700, 500))
        self.taskList.setObjectName("taskList")
        self.taskList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)  # Enable multiple selection (checkboxes)
        self.taskList.setStyleSheet(
            "QListWidget {\n"
            "   font-size: 20pt;\n"
            "   border: 2px solid black;\n"
            "   border-radius: 5px;\n"
            "   background-color: #ECECEC;\n"
            "   border-radius: 5px;\n"
            "}\n"
            "\n"
        )

        # menu button
        self.btn_menu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_menu.setGeometry(QtCore.QRect(40, 40, 151, 41))
        self.btn_menu.setObjectName("btn_menu")
        self.btn_menu.setText("Back to menu")
        self.btn_menu.setStyleSheet(
            "QPushButton {\n"
            "    color: black;\n"
            "    border: 2px solid black;\n"
            "    border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #d3d3d3;\n"
            "}\n"
            ""
        )
        self.btn_menu.clicked.connect(TaskPage.close)
        
        # Predefined tasks to be displayed in the task list
        premade_tasks = [
            "Task 1: Learn Python",
            "Task 2: Complete homework",
            "Task 3: Study for exam",
            "Task 4: Organize desk",
            "Task 5: Read a book"
        ]
        
        # Add each task to the list with an initial unchecked state
        for task in premade_tasks:
            item = QtWidgets.QListWidgetItem(task)
            item.setCheckState(QtCore.Qt.Unchecked)  # Initially unchecked
            self.taskList.addItem(item)
        
        # Connect the itemChanged signal to the updatePoints function
        self.taskList.itemChanged.connect(self.updatePoints)

        # Set the central widget for the main window
        TaskPage.setCentralWidget(self.centralwidget)
        
        # Menu bar (currently empty but can be populated later if needed)
        self.menubar = QtWidgets.QMenuBar(TaskPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        TaskPage.setMenuBar(self.menubar)
        
        # Status bar (for displaying messages)
        self.statusbar = QtWidgets.QStatusBar(TaskPage)
        self.statusbar.setObjectName("statusbar")
        TaskPage.setStatusBar(self.statusbar)     

    def saveProgress(self):
        """Save the progress (task states and points) to a file using pickle."""
        # Create a dictionary with tasks and points to store
        data = {
            'tasks': [(self.taskList.item(i).text(), self.taskList.item(i).checkState()) for i in range(self.taskList.count())],
            'points': self.pointsLabel.text().split(': ')[1]  # Extract points from the label
        }
        
        # Write the data to a file (task_progress.pkl)
        with open('task_progress.pkl', 'wb') as file:
            pickle.dump(data, file)

    def loadProgress(self):
        """Load saved progress (tasks and points) from a file."""
        try:
            # Try to load saved progress from file
            with open('task_progress.pkl', 'rb') as file:
                data = pickle.load(file)
                tasks = data.get('tasks', [])
                points = data.get('points', '0')
                
                # Clear the current tasks before loading new ones
                self.taskList.clear()
                
                # Add the saved tasks back to the list with their respective check states
                for task, checkState in tasks:
                    item = QtWidgets.QListWidgetItem(task)
                    item.setCheckState(checkState)  # Set the saved check state for each task
                    self.taskList.addItem(item)
                    
                # Set the points label based on the saved points
                self.pointsLabel.setText(f"Points: {points}")
        except FileNotFoundError:
            # If no saved progress file exists, do nothing
            pass

    def resetEverything(self):
        """Clear all tasks and reset points to zero."""
        self.taskList.clear()
        self.pointsLabel.setText("Points: 0")

    def updatePoints(self):
        """Update the points based on the number of tasks checked."""
        points = 0
        for i in range(self.taskList.count()):
            if self.taskList.item(i).checkState() == QtCore.Qt.Checked:
                points += 1  # Add 1 point for each checked task
        self.pointsLabel.setText(f"Points: {points}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TaskPage = QtWidgets.QMainWindow()
    ui = Ui_TaskPage()
    ui.setupUi(TaskPage)
    ui.loadProgress()  # Load progress when the application starts
    TaskPage.show()
    sys.exit(app.exec_())
